name: what_was_it_app
description: what was it - application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  flutter_riverpod: ^1.0.4
  clickable_list_wheel_view: ^0.1.0
  shared_preferences: ^2.0.15
  syncfusion_flutter_datepicker: ^20.2.40
  flutter_local_notifications: ^9.7.0
  flutter_phoenix: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - images/what_was_it_main.png

  fonts:
    - family: GowunDodum
      fonts:
        - asset: fonts/GowunDodum-Regular.ttf
